pref("extensions.RRprintPages2Pdf.wkhtml.gopt.size.pageSize", "A4");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.size.width", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.size.height", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.orientation", "Portrait");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.colorMode", "Color");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.pageOffset", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.outline", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.outlineDepth", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.dumpOutline", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.documentTitle", "Created By Print Pages to Pdf");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.useCompression", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.margin.top", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.margin.right", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.margin.left", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.margin.bottom", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.outputFormat", "pdf");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.imageDPI", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.dpi", "-1");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.imageQuality", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.load.cookieJar", "");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.guessPageLength", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.gopt.resolution", "high");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.pageunits", "cm");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.useScreenDpi", "true");

pref("extensions.RRprintPages2Pdf.wkhtml.iopt.toc.createToc", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.useDottedLines", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.captionText", "");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.forwardLinks", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.backLinks", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.indentation", "");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.toc.fontScale", "");
pref("extensions.RRprintPages2Pdf.wkhtml.topt.tocXsl", "");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.isTableOfContent", "false");

pref("extensions.RRprintPages2Pdf.wkhtml.iopt.coverFile", "");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.useCover", "false");

pref("extensions.RRprintPages2Pdf.wkhtml.oopt.useExternalLinks", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.useLocalLinks", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.produceForms", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.includeInOutline", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.pagesCount", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.background", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.loadImages", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.enableJavascript", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.enableIntelligentShrinking", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.minimumFontSize", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.printMediaType", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.defaultEncoding", "utf-8");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.userStyleSheet", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.web.enablePlugins", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.username", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.password", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.jsdelay", "5000");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.zoomFactor", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.repeatCustomHeaders", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.blockLocalFileAccess", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.stopSlowScript", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.debugJavascript", "false");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.load.loadErrorHandling", "ignore");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.fontSize", "6");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.fontName", "Avant Garde Gothic");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.left", "[title]");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.center", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.right", "[date]");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.line", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.spacing", "5");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.header.htmlUrl", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.fontSize", "6");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.fontName", "Avant Garde Gothic");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.left", "[webpage]");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.center", "");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.right", "[page] / [topage]");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.line", "true");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.spacing", "5");
pref("extensions.RRprintPages2Pdf.wkhtml.oopt.footer.htmlUrl", "");

pref("extensions.RRprintPages2Pdf.wkhtml.iopt.outline.titleOnly","false");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.pageload.timeout","9000");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.pageload.minLocal","true");
pref("extensions.RRprintPages2Pdf.wkhtml.iopt.useScreenResolution","true");

pref("extensions.RRprintPages2Pdf.processing.openConvertResult", true);
pref("extensions.RRprintPages2Pdf.processing.closeDlgAfterConversion", true);
pref("extensions.RRprintPages2Pdf.processing.closeDlgAfterConversion.ask", false);
pref("extensions.RRprintPages2Pdf.processing.closeDlgOnWarning", true);
pref("extensions.RRprintPages2Pdf.processing.startConvImmediately", true);
pref("extensions.RRprintPages2Pdf.processing.convSeparate", false);
pref("extensions.RRprintPages2Pdf.processing.convSeparate.ask", false);
pref("extensions.RRprintPages2Pdf.ui.toolbarbuttons", "full");
pref("extensions.RRprintPages2Pdf.ui.showsbmenus", true);
pref("extensions.RRprintPages2Pdf.ui.showplacesmenus", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.printActiveTab", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.printActiveTabText", false);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.printAllTabs", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.printAllTabsText", false);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.printSelection", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.openProcessDlg", false);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.openPrefsDlg", false);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.toggleSidebar", true);
pref("extensions.RRprintPages2Pdf.ui.showpagemenus.help", true);

pref("extensions.RRprintPages2Pdf.ui.showextramenus", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.printActiveTab", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.printActiveTabText", false);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.printAllTabs", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.printAllTabsText", false);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.printSelection", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.openProcessDlg", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.openPrefsDlg", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.toggleSidebar", true);
pref("extensions.RRprintPages2Pdf.ui.showextramenus.help", true);

pref("extensions.RRprintPages2Pdf.ui.showtbbmenus", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.printActiveTab", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.printActiveTabText", false);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.printAllTabs", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.printAllTabsText", false);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.printSelection", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.openProcessDlg", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.openPrefsDlg", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.toggleSidebar", true);
pref("extensions.RRprintPages2Pdf.ui.showtbbmenus.help", true);

pref("extensions.RRprintPages2Pdf.ui.showtabmenu", true);
pref("extensions.RRprintPages2Pdf.ui.tbbfunction", "alltabs");
pref("extensions.RRprintPages2Pdf.ui.helpsite", "http://printpagestopdf.hol.es;http://printpagestopdf.lima-city.de;http://printpagestopdf.kilu.de");

pref("extensions.RRprintPages2Pdf.processing.outputDir", "");
pref("extensions.RRprintPages2Pdf.processing.pdfViewer", "");
pref("extensions.RRprintPages2Pdf.processing.maxOutFileLength", "60");

pref("extensions.RRprintPages2Pdf.archive.preview", false);
pref("extensions.RRprintPages2Pdf.archive.showthumbs", true);
pref("extensions.RRprintPages2Pdf.archive.thumbsquality", "60");
pref("extensions.RRprintPages2Pdf.archive.showMyDocuments", true);
pref("extensions.RRprintPages2Pdf.archive.showRecent", true);

pref("extensions.RRprintPages2Pdf.sc.menmain_shift", true);
pref("extensions.RRprintPages2Pdf.sc.menmain_alt" , false);
pref("extensions.RRprintPages2Pdf.sc.menmain_ctrl" , true);
pref("extensions.RRprintPages2Pdf.sc.menmain_key", "Q");

pref("extensions.RRprintPages2Pdf.sc.prtabs_shift" , false);
pref("extensions.RRprintPages2Pdf.sc.prtabs_alt" , false);
pref("extensions.RRprintPages2Pdf.sc.prtabs_ctrl" , false);
pref("extensions.RRprintPages2Pdf.sc.prtabs_key", "");

pref("extensions.RRprintPages2Pdf.sc.prpage_shift" , false);
pref("extensions.RRprintPages2Pdf.sc.prpage_alt" , false);
pref("extensions.RRprintPages2Pdf.sc.prpage_ctrl" , false);
pref("extensions.RRprintPages2Pdf.sc.prpage_key", "");

pref("extensions.RRprintPages2Pdf.sc.sidebar_shift" , false);
pref("extensions.RRprintPages2Pdf.sc.sidebar_alt" , true);
pref("extensions.RRprintPages2Pdf.sc.sidebar_ctrl" , false);
pref("extensions.RRprintPages2Pdf.sc.sidebar_key", "p");
